name: Consumer Compatibility Check

on: [push, pull_request]

jobs:
  compat-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-type: [nodenext, bundler, commonjs, iife] # package.json scripts
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm' # Caches node_modules for faster runs
      - name: Install dependencies
        run: npm ci
      - name: Prepare Playwright (for iife test)
        run: npm run test:prepare # Installs Chromium and deps
      - name: Run ${{ matrix.test-type }} Test
        run: npm run test:${{ matrix.test-type }}
