name: CI Test Workflow

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Compose
        uses: adambirds/docker-compose-action@v1.3.0
      - name: Checkout Nutshell repository
        uses: actions/checkout@v2
        with:
          repository: 'cashubtc/nutshell'
          ref: 'docker-network-mode-host'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and start mint
        run: |
          docker-compose up -d
      - name: Curl on localhost:3338/keys
        run: curl http://localhost:3338/keys
      - name: Navigate to the parent directory
        run: cd ..
      - uses: actions/checkout@v3

      - name: Run Tests
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - run: npm ci
      - run: npm run compile
      - run: npm run test-integration
