name: CI Test Workflow

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: 'cashubtc/nutshell'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build and start services
        run: |
          docker-compose up -d
      - name: Check if services are running
        run: netstat -lp
      - name: Run ifconfig
        run: ifconfig
      - name: Curl on localhost:4448/keys
        run: curl http://127.0.0.1:4448/

      - name: Curl on localhost:3338/keys
        run: curl http://127.0.0.1:3338/keys

      - name: Navigate to the parent directory
        run: cd ..
      - uses: actions/checkout@v3

      - name: Run Tests
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - run: npm ci
      - run: npm run compile
      - run: npm run test-integration
