name: CI Test Workflow

# on: [push, pull_request]
on: []

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Checkout Nutshell repository
        uses: actions/checkout@v2
        with:
          repository: 'cashubtc/nutshell'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and start mint
        run: |
          docker-compose up -d
      - name: Run netstat
        run: netstat -lp
      - name: Curl on localhost:3338/keys
        run: curl http://localhost:3338/keys
      - name: Navigate to the parent directory
        run: cd ..
      - name: Checkout cashu-ts repository
        uses: actions/checkout@v3

      - name: Run Tests
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - run: npm ci
      - run: npm run compile
      - run: npm run test-integration
