# A GitHub Actions workflow that generates the documentation for pull requests

name: tsdoc-markdown

on:
  push:
permissions:
  contents: write
jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npx typedoc $(find  'src' -type f -name '*.ts' -not -name '*.test.ts' -printf "%p ") --out docs
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: docs